#ifndef _COMMON_HEADER_H_
#define _COMMON_HEADER_H_

#include <Arduino.h>

namespace common
{
    enum class error_type_t
    {
        SUCCESS,
        FAILURE,
        INVALID_PIN,
        NULL_PARAMETER,
        COMMUNICATION_ERROR,
        INVALID_ID,
        INVALID_FUNCTION,
        INVALID_PARAMETER,
        INVALID_QUANTITY,
        FRAME_ERROR,
        CRC_ERROR,
        UNEXPECTED_BYTE_COUNT,
        INIT_FAIL,
        TX_ERROR,
        ERROR_TIMEOUT,
        RX_ERROR,
        ERROR_NONE,
        ERROR_NOT_INITIALIZED,
        ERROR_ALREADY_INITIALIZED,
        PRESSURE_READ_ERROR,
        ERROR_FILE_LOADING_FAILED,
        ERROR_FILE_PARSE_FAILED,
        ERROR_FILE_OPEN_FAILED,
        FILE_SAVED,
        CARD_MOUNT_FAILED,
        NO_CARD_ATTACHED,
        CARD_SUCCESSFUL,
        WRITE_SUCCESSFUL,
        FILE_READ_SUCCESS,
        FILE_APPEND_SUCCESS,
        ERROR_FILE_NOT_FOUND,
        ERROR_FILE_READ_FAILED,
        ERROR_JSON_PARSE_FAILED,
        ERROR_FILE_WRITE_FAILED,
        ERROR_FILE_EMPTY
    };
}

#endif 
